version: "3.9"  # optional since v1.27.0 # con docker host.docker.internal
services: 
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DB: dan2021
    volumes:
      - ./mys-data:/var/lib/mysql/data
      - ./ESQUEMA_DAN_01.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - infra
      - app       
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - infra
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mg-data/datadb:/data/db
      - ./mg-data/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dan2021
      MONGO_INITDB_ROOT_PASSWORD: dan2021
    ports:
    - 27017:27017
    networks:
      - infra
      - app
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dan2021
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dan2021
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - infra
  artemis:
    container_name: artemis
    build:
      context: .\artemis
      dockerfile: Dockerfile
    ports:
      - 6003:8161
    restart: always
    networks:
      - infra
      - app      
networks:
    infra:
        driver: bridge
    app:
        driver: bridge    